server:
  port: 8080

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/patientdb
    username: root
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
