server:
  port: 8082

spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://localhost:3306/appointmentdb
    username: root
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka


